sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bhm-kyndryl/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bhm-kyndryl/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-015806071036"
  bucket_path: "docker-react"
  on:
    repo: bhm-kyndryl/docker-react
    branches:
      only:
        - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    

    